---
- name: Deploy nginx configuration
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
    backup: false
  loop:
    - etc/nginx/nginx.conf
    - etc/nginx/sites-available/isucon.conf
  notify: restart_nginx
- name: Enable target nginx site
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/isucon.conf
    dest: /etc/nginx/sites-enabled/isucon.conf
    state: link
    owner: root
    group: root
  notify: restart_nginx
