---
- name: Run benchmark from the benchmarker host
  hosts: benchmarker
  become: true
  tasks:
    - name: Run benchmark and collect its log
      ansible.builtin.import_role:
        name: bench
        tasks_from: run
